### PR TITLE
Added two props (title and it's style)

### PR DESCRIPTION
**Pull request by parazitenew**
Sometime, users forget on which option they clicked on. A title prop on the SelectPicker is useful.

Added two props:
titleText
titleTextStyle

Maybe it needs a new release (0.0.11)

### CODE REVIEW

**Comment by olayinkaokewale** [comment]
@parazitenew can you please include the screenshot of the title you added so we can be sure of what was added. You can also increase the version number to `0.0.12` inside of the `package.json` file. Thanks

**Comment by parazitenew** [comment]
Screenshot_2021-03-19-17-06-33-710_com

**Comment by parazitenew** [comment]
Hi,

I sent a screenshot in the pull request conversation. I updated the packages.json and README.md, and sent the changes with the desktop github software. There is a conflict withe theses two files. Sorry I'm new to github.


M. RAMDANI IMED
+213 550 76 74 28

________________________________
De : Olayinka Okewale ***@***.***>
Envoyé : vendredi 19 mars 2021 17:00
À : olayinkaokewale/react-native-select-picker ***@***.***>
Cc : Imed Ramdani ***@***.***>; Mention ***@***.***>
Objet : Re: [olayinkaokewale/react-native-select-picker] Added two props (title and it's style) (#13)


@parazitenew<https://github.com/parazitenew> can you please include the screenshot of the title you added so we can be sure of what was added. You can also increase the version number to 0.0.12 inside of the package.json file. Thanks

**Comment by olayinkaokewale** [comment]
@parazitenew nice. There's no conflict here so I will merge and deploy your changes. Thanks

**Pull request merged**
